declare namespace Form.si_service.Main {
  namespace Information {
    namespace Tabs {
      interface GeneralTab extends Xrm.SectionCollectionBase {
        get(name: "secBasicServiceData"): Xrm.PageSection;
        get(name: "secServiceDetails"): Xrm.PageSection;
        get(name: "secServiceDigitizationDelivery"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tabChildrenServices extends Xrm.SectionCollectionBase {
        get(name: "tab_5_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tabServiceStandard extends Xrm.SectionCollectionBase {
        get(name: "tab_4_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tabServiceStandardFee extends Xrm.SectionCollectionBase {
        get(name: "tab_3_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_2 extends Xrm.SectionCollectionBase {
        get(name: "tab_2_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "si_accesstype"): Xrm.LookupAttribute<"si_accesstype">;
      get(name: "si_associatedadm"): Xrm.OptionSetAttribute<si_associatedadm>;
      get(name: "si_associatedtoservicestandards"): Xrm.Attribute<any>;
      get(name: "si_businessline"): Xrm.LookupAttribute<"si_businessline">;
      get(name: "si_channelserviceisoffered"): Xrm.MultiSelectOptionSetAttribute<si_feedbackonlevelofsatisfaction>;
      get(name: "si_clientfeedbackbychannel"): Xrm.MultiSelectOptionSetAttribute<si_feedbackonlevelofsatisfaction>;
      get(name: "si_clienttargetgroup"): Xrm.LookupAttribute<"si_clienttargetgroup">;
      get(name: "si_commentsdigitalenterpriseidentityplatform"): Xrm.Attribute<string>;
      get(name: "si_directorate"): Xrm.LookupAttribute<"si_directorate">;
      get(name: "si_englishcomments"): Xrm.Attribute<string>;
      get(name: "si_englishcommentsrelatedtoonlineservices"): Xrm.Attribute<string>;
      get(name: "si_englishdescription"): Xrm.Attribute<string>;
      get(name: "si_frenchcomments"): Xrm.Attribute<string>;
      get(name: "si_frenchcommentsrelatedtoonlineservices"): Xrm.Attribute<string>;
      get(name: "si_frenchdescription"): Xrm.Attribute<string>;
      get(name: "si_id"): Xrm.Attribute<string>;
      get(name: "si_lastgbaanalysiscompletedsince20142015"): Xrm.Attribute<string>;
      get(name: "si_nameen"): Xrm.Attribute<string>;
      get(name: "si_namefr"): Xrm.Attribute<string>;
      get(name: "si_numberofapplicationsbymail"): Xrm.NumberAttribute;
      get(name: "si_numberofapplicationsbytelephone"): Xrm.NumberAttribute;
      get(name: "si_numberofapplicationsthroughotherchannels"): Xrm.NumberAttribute;
      get(name: "si_numberofinpersonapplications"): Xrm.NumberAttribute;
      get(name: "si_numberofonlineapplications"): Xrm.NumberAttribute;
      get(name: "si_numberoftelephoneinquires"): Xrm.NumberAttribute;
      get(name: "si_numberofwebsitevisits"): Xrm.NumberAttribute;
      get(name: "si_parentservice"): Xrm.LookupAttribute<"si_service">;
      get(name: "si_piacompleted"): Xrm.Attribute<any>;
      get(name: "si_program"): Xrm.LookupAttribute<"si_program">;
      get(name: "si_servicefee"): Xrm.Attribute<any>;
      get(name: "si_servicegroup"): Xrm.LookupAttribute<"si_servicegroup">;
      get(name: "si_servicestatus"): Xrm.OptionSetAttribute<si_servicestatus>;
      get(name: "si_servicetype"): Xrm.LookupAttribute<"si_servicetype">;
      get(name: "si_specialdesignation"): Xrm.LookupAttribute<"si_specialdesignation">;
      get(name: "si_totalannualvolume"): Xrm.NumberAttribute;
      get(name: "si_urltoenglishpage"): Xrm.Attribute<string>;
      get(name: "si_urltofrenchpage"): Xrm.Attribute<string>;
      get(name: "si_utilizescrabusinessnumber"): Xrm.Attribute<any>;
      get(name: "si_utilizeseauthentication"): Xrm.Attribute<any>;
      get(name: "si_utilizesedecision"): Xrm.Attribute<any>;
      get(name: "si_utilizeseissuance"): Xrm.Attribute<any>;
      get(name: "si_utilizesentdigitalidentityplatform"): Xrm.Attribute<any>;
      get(name: "si_utilizeseregistration"): Xrm.Attribute<any>;
      get(name: "si_utilizeseresolution"): Xrm.Attribute<any>;
      get(name: "si_utilizessinnumber"): Xrm.Attribute<any>;
      get(name: "si_utlilizeseapplication"): Xrm.Attribute<any>;
      get(name: "si_yearoflastpia"): Xrm.Attribute<string>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "gridChildrenServices"): Xrm.SubGridControl<"si_service">;
      get(name: "gridServiceStandard"): Xrm.SubGridControl<"si_servicestandard">;
      get(name: "gridServiceStandardAndFee"): Xrm.SubGridControl<"si_serviceservicestandardfee">;
      get(name: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "si_accesstype"): Xrm.LookupControl<"si_accesstype">;
      get(name: "si_associatedadm"): Xrm.OptionSetControl<si_associatedadm>;
      get(name: "si_associatedtoservicestandards"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_businessline"): Xrm.LookupControl<"si_businessline">;
      get(name: "si_channelserviceisoffered"): Xrm.MultiSelectOptionSetControl<si_feedbackonlevelofsatisfaction>;
      get(name: "si_clientfeedbackbychannel"): Xrm.MultiSelectOptionSetControl<si_feedbackonlevelofsatisfaction>;
      get(name: "si_clienttargetgroup"): Xrm.LookupControl<"si_clienttargetgroup">;
      get(name: "si_commentsdigitalenterpriseidentityplatform"): Xrm.StringControl;
      get(name: "si_directorate"): Xrm.LookupControl<"si_directorate">;
      get(name: "si_englishcomments"): Xrm.StringControl;
      get(name: "si_englishcommentsrelatedtoonlineservices"): Xrm.StringControl;
      get(name: "si_englishdescription"): Xrm.StringControl;
      get(name: "si_frenchcomments"): Xrm.StringControl;
      get(name: "si_frenchcommentsrelatedtoonlineservices"): Xrm.StringControl;
      get(name: "si_frenchdescription"): Xrm.StringControl;
      get(name: "si_id"): Xrm.StringControl;
      get(name: "si_lastgbaanalysiscompletedsince20142015"): Xrm.StringControl;
      get(name: "si_nameen"): Xrm.StringControl;
      get(name: "si_namefr"): Xrm.StringControl;
      get(name: "si_numberofapplicationsbymail"): Xrm.NumberControl;
      get(name: "si_numberofapplicationsbytelephone"): Xrm.NumberControl;
      get(name: "si_numberofapplicationsthroughotherchannels"): Xrm.NumberControl;
      get(name: "si_numberofinpersonapplications"): Xrm.NumberControl;
      get(name: "si_numberofonlineapplications"): Xrm.NumberControl;
      get(name: "si_numberoftelephoneinquires"): Xrm.NumberControl;
      get(name: "si_numberofwebsitevisits"): Xrm.NumberControl;
      get(name: "si_parentservice"): Xrm.LookupControl<"si_service">;
      get(name: "si_piacompleted"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_program"): Xrm.LookupControl<"si_program">;
      get(name: "si_servicefee"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_servicegroup"): Xrm.LookupControl<"si_servicegroup">;
      get(name: "si_servicestatus"): Xrm.OptionSetControl<si_servicestatus>;
      get(name: "si_servicetype"): Xrm.LookupControl<"si_servicetype">;
      get(name: "si_specialdesignation"): Xrm.LookupControl<"si_specialdesignation">;
      get(name: "si_totalannualvolume"): Xrm.NumberControl;
      get(name: "si_urltoenglishpage"): Xrm.StringControl;
      get(name: "si_urltofrenchpage"): Xrm.StringControl;
      get(name: "si_utilizescrabusinessnumber"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_utilizeseauthentication"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_utilizesedecision"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_utilizeseissuance"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_utilizesentdigitalidentityplatform"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_utilizeseregistration"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_utilizeseresolution"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_utilizessinnumber"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_utlilizeseapplication"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "si_yearoflastpia"): Xrm.StringControl;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "GeneralTab"): Xrm.PageTab<Tabs.GeneralTab>;
      get(name: "tabChildrenServices"): Xrm.PageTab<Tabs.tabChildrenServices>;
      get(name: "tabServiceStandard"): Xrm.PageTab<Tabs.tabServiceStandard>;
      get(name: "tabServiceStandardFee"): Xrm.PageTab<Tabs.tabServiceStandardFee>;
      get(name: "tab_2"): Xrm.PageTab<Tabs.tab_2>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "si_accesstype"): Xrm.LookupAttribute<"si_accesstype">;
    getAttribute(attributeName: "si_associatedadm"): Xrm.OptionSetAttribute<si_associatedadm>;
    getAttribute(attributeName: "si_associatedtoservicestandards"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_businessline"): Xrm.LookupAttribute<"si_businessline">;
    getAttribute(attributeName: "si_channelserviceisoffered"): Xrm.MultiSelectOptionSetAttribute<si_feedbackonlevelofsatisfaction>;
    getAttribute(attributeName: "si_clientfeedbackbychannel"): Xrm.MultiSelectOptionSetAttribute<si_feedbackonlevelofsatisfaction>;
    getAttribute(attributeName: "si_clienttargetgroup"): Xrm.LookupAttribute<"si_clienttargetgroup">;
    getAttribute(attributeName: "si_commentsdigitalenterpriseidentityplatform"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_directorate"): Xrm.LookupAttribute<"si_directorate">;
    getAttribute(attributeName: "si_englishcomments"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_englishcommentsrelatedtoonlineservices"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_englishdescription"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_frenchcomments"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_frenchcommentsrelatedtoonlineservices"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_frenchdescription"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_id"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_lastgbaanalysiscompletedsince20142015"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_nameen"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_namefr"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_numberofapplicationsbymail"): Xrm.NumberAttribute;
    getAttribute(attributeName: "si_numberofapplicationsbytelephone"): Xrm.NumberAttribute;
    getAttribute(attributeName: "si_numberofapplicationsthroughotherchannels"): Xrm.NumberAttribute;
    getAttribute(attributeName: "si_numberofinpersonapplications"): Xrm.NumberAttribute;
    getAttribute(attributeName: "si_numberofonlineapplications"): Xrm.NumberAttribute;
    getAttribute(attributeName: "si_numberoftelephoneinquires"): Xrm.NumberAttribute;
    getAttribute(attributeName: "si_numberofwebsitevisits"): Xrm.NumberAttribute;
    getAttribute(attributeName: "si_parentservice"): Xrm.LookupAttribute<"si_service">;
    getAttribute(attributeName: "si_piacompleted"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_program"): Xrm.LookupAttribute<"si_program">;
    getAttribute(attributeName: "si_servicefee"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_servicegroup"): Xrm.LookupAttribute<"si_servicegroup">;
    getAttribute(attributeName: "si_servicestatus"): Xrm.OptionSetAttribute<si_servicestatus>;
    getAttribute(attributeName: "si_servicetype"): Xrm.LookupAttribute<"si_servicetype">;
    getAttribute(attributeName: "si_specialdesignation"): Xrm.LookupAttribute<"si_specialdesignation">;
    getAttribute(attributeName: "si_totalannualvolume"): Xrm.NumberAttribute;
    getAttribute(attributeName: "si_urltoenglishpage"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_urltofrenchpage"): Xrm.Attribute<string>;
    getAttribute(attributeName: "si_utilizescrabusinessnumber"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_utilizeseauthentication"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_utilizesedecision"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_utilizeseissuance"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_utilizesentdigitalidentityplatform"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_utilizeseregistration"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_utilizeseresolution"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_utilizessinnumber"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_utlilizeseapplication"): Xrm.Attribute<any>;
    getAttribute(attributeName: "si_yearoflastpia"): Xrm.Attribute<string>;
    getAttribute(attributeName: string): undefined;
    getControl(controlName: "gridChildrenServices"): Xrm.SubGridControl<"si_service">;
    getControl(controlName: "gridServiceStandard"): Xrm.SubGridControl<"si_servicestandard">;
    getControl(controlName: "gridServiceStandardAndFee"): Xrm.SubGridControl<"si_serviceservicestandardfee">;
    getControl(controlName: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "si_accesstype"): Xrm.LookupControl<"si_accesstype">;
    getControl(controlName: "si_associatedadm"): Xrm.OptionSetControl<si_associatedadm>;
    getControl(controlName: "si_associatedtoservicestandards"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_businessline"): Xrm.LookupControl<"si_businessline">;
    getControl(controlName: "si_channelserviceisoffered"): Xrm.MultiSelectOptionSetControl<si_feedbackonlevelofsatisfaction>;
    getControl(controlName: "si_clientfeedbackbychannel"): Xrm.MultiSelectOptionSetControl<si_feedbackonlevelofsatisfaction>;
    getControl(controlName: "si_clienttargetgroup"): Xrm.LookupControl<"si_clienttargetgroup">;
    getControl(controlName: "si_commentsdigitalenterpriseidentityplatform"): Xrm.StringControl;
    getControl(controlName: "si_directorate"): Xrm.LookupControl<"si_directorate">;
    getControl(controlName: "si_englishcomments"): Xrm.StringControl;
    getControl(controlName: "si_englishcommentsrelatedtoonlineservices"): Xrm.StringControl;
    getControl(controlName: "si_englishdescription"): Xrm.StringControl;
    getControl(controlName: "si_frenchcomments"): Xrm.StringControl;
    getControl(controlName: "si_frenchcommentsrelatedtoonlineservices"): Xrm.StringControl;
    getControl(controlName: "si_frenchdescription"): Xrm.StringControl;
    getControl(controlName: "si_id"): Xrm.StringControl;
    getControl(controlName: "si_lastgbaanalysiscompletedsince20142015"): Xrm.StringControl;
    getControl(controlName: "si_nameen"): Xrm.StringControl;
    getControl(controlName: "si_namefr"): Xrm.StringControl;
    getControl(controlName: "si_numberofapplicationsbymail"): Xrm.NumberControl;
    getControl(controlName: "si_numberofapplicationsbytelephone"): Xrm.NumberControl;
    getControl(controlName: "si_numberofapplicationsthroughotherchannels"): Xrm.NumberControl;
    getControl(controlName: "si_numberofinpersonapplications"): Xrm.NumberControl;
    getControl(controlName: "si_numberofonlineapplications"): Xrm.NumberControl;
    getControl(controlName: "si_numberoftelephoneinquires"): Xrm.NumberControl;
    getControl(controlName: "si_numberofwebsitevisits"): Xrm.NumberControl;
    getControl(controlName: "si_parentservice"): Xrm.LookupControl<"si_service">;
    getControl(controlName: "si_piacompleted"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_program"): Xrm.LookupControl<"si_program">;
    getControl(controlName: "si_servicefee"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_servicegroup"): Xrm.LookupControl<"si_servicegroup">;
    getControl(controlName: "si_servicestatus"): Xrm.OptionSetControl<si_servicestatus>;
    getControl(controlName: "si_servicetype"): Xrm.LookupControl<"si_servicetype">;
    getControl(controlName: "si_specialdesignation"): Xrm.LookupControl<"si_specialdesignation">;
    getControl(controlName: "si_totalannualvolume"): Xrm.NumberControl;
    getControl(controlName: "si_urltoenglishpage"): Xrm.StringControl;
    getControl(controlName: "si_urltofrenchpage"): Xrm.StringControl;
    getControl(controlName: "si_utilizescrabusinessnumber"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_utilizeseauthentication"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_utilizesedecision"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_utilizeseissuance"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_utilizesentdigitalidentityplatform"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_utilizeseregistration"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_utilizeseresolution"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_utilizessinnumber"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_utlilizeseapplication"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "si_yearoflastpia"): Xrm.StringControl;
    getControl(controlName: string): undefined;
  }
}
